root ::= break? sep? ((comment | command) (break sep? | <eof>))*
word ::= (!sep [^(){}:?*,=\[\]])+
sep ::= [ \t]+
break ::= (sep? "\n")+
comment ::= "//" [^\n]*

flag ::= "-" word ("," word)*
escapeSequence ::= "\\" [^]
constraint ::= "<" (escapeSequence | [^<>])* ">"
defaultValue ::= "(" (escapeSequence | [^()])* ")"
arg ::= word constraint? ("..." | "[]")? ":" word ("?" defaultValue?)?
cmdName ::= word ("," word)*
param ::= flag | arg
paramList ::= (sep param)*

tag ::= word (sep? "=" sep? [^{}\n]+) sep?
entry ::= sep? (tag | command | comment) comment? break

command ::= cmdName paramList break? sep? commandBody
commandBody ::= "{" comment? break? entry* "}" break?