root ::= command*
word ::= [^\[\](){}:?*,=]+
sep ::= [ \t]+
break ::= (sep? "\n")+

flag ::= "-" word ("," word)*
constraint ::= "<" ("\\" [^] | [^<>])* ">"
defaultValue ::= "(" ("\\" [^] | [^()])* ")"
arg ::= word constraint? ("..." | "[]")? ":" word ("?" defaultValue?)?
cmdName ::= word ("," word)*
param ::= flag | arg
paramList ::= (sep param)*

tag ::= word (sep? "=" sep? [^{}\n]+) sep?
entry ::= (tag "\n"? | command) break

command ::= cmdName paramList sep? commandBody
commandBody ::= "{" break? entry* "}" break?